/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Conversation {
  'id' : ConversationId,
  'participants' : Array<UserId>,
  'messages' : Array<Message>,
  'isGroup' : boolean,
  'groupName' : [] | [string],
}
export type ConversationId = bigint;
export interface Message {
  'id' : MessageId,
  'content' : string,
  'read' : boolean,
  'sender' : UserId,
  'timestamp' : Time,
}
export type MessageId = bigint;
export type Time = bigint;
export type UserId = Principal;
export interface UserProfile {
  'status' : UserStatus,
  'displayName' : string,
  'userId' : UserId,
  'avatarUrl' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserStatus = { 'away' : null } |
  { 'busy' : null } |
  { 'offline' : null } |
  { 'online' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Add a contact to the caller's contact list.
   */
  'addContact' : ActorMethod<[UserId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Create a new conversation. The caller is automatically added as a participant.
   */
  'createConversation' : ActorMethod<
    [Array<UserId>, boolean, [] | [string]],
    ConversationId
  >,
  /**
   * / Get the calling user's own profile.
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Get the caller's contact list.
   */
  'getContacts' : ActorMethod<[], Array<UserId>>,
  /**
   * / Get all conversations the caller participates in.
   */
  'getConversations' : ActorMethod<[], Array<Conversation>>,
  /**
   * / Get messages from a conversation. Caller must be a participant.
   */
  'getMessages' : ActorMethod<[ConversationId, bigint, bigint], Array<Message>>,
  /**
   * / Get the calling user's own profile (convenience alias).
   */
  'getMyProfile' : ActorMethod<[], UserProfile>,
  /**
   * / Fetch any user's profile. Accessible to registered users.
   */
  'getUserProfile' : ActorMethod<[UserId], UserProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Mark all messages in a conversation as read for the caller. Caller must be a participant.
   */
  'markMessagesRead' : ActorMethod<[ConversationId], undefined>,
  /**
   * / Register a new user. Creates an initial profile; no role assignment needed
   * / since registration is gated by profile existence checks.
   */
  'registerUser' : ActorMethod<[string, string], undefined>,
  /**
   * / Remove a contact from the caller's contact list.
   */
  'removeContact' : ActorMethod<[UserId], undefined>,
  /**
   * / Save (upsert) the calling user's own profile.
   */
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Send a message to a conversation. Caller must be a participant.
   */
  'sendMessage' : ActorMethod<[ConversationId, string], MessageId>,
  /**
   * / Update the calling user's display name and avatar URL.
   */
  'updateProfile' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];