/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ConversationId = IDL.Nat;
export const UserStatus = IDL.Variant({
  'away' : IDL.Null,
  'busy' : IDL.Null,
  'offline' : IDL.Null,
  'online' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'status' : UserStatus,
  'displayName' : IDL.Text,
  'userId' : UserId,
  'avatarUrl' : IDL.Text,
});
export const MessageId = IDL.Nat;
export const Time = IDL.Int;
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'read' : IDL.Bool,
  'sender' : UserId,
  'timestamp' : Time,
});
export const Conversation = IDL.Record({
  'id' : ConversationId,
  'participants' : IDL.Vec(UserId),
  'messages' : IDL.Vec(Message),
  'isGroup' : IDL.Bool,
  'groupName' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addContact' : IDL.Func([UserId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createConversation' : IDL.Func(
      [IDL.Vec(UserId), IDL.Bool, IDL.Opt(IDL.Text)],
      [ConversationId],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContacts' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
  'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'getMessages' : IDL.Func(
      [ConversationId, IDL.Nat, IDL.Nat],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([], [UserProfile], ['query']),
  'getUserProfile' : IDL.Func([UserId], [UserProfile], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markMessagesRead' : IDL.Func([ConversationId], [], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removeContact' : IDL.Func([UserId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([ConversationId, IDL.Text], [MessageId], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ConversationId = IDL.Nat;
  const UserStatus = IDL.Variant({
    'away' : IDL.Null,
    'busy' : IDL.Null,
    'offline' : IDL.Null,
    'online' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'status' : UserStatus,
    'displayName' : IDL.Text,
    'userId' : UserId,
    'avatarUrl' : IDL.Text,
  });
  const MessageId = IDL.Nat;
  const Time = IDL.Int;
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'read' : IDL.Bool,
    'sender' : UserId,
    'timestamp' : Time,
  });
  const Conversation = IDL.Record({
    'id' : ConversationId,
    'participants' : IDL.Vec(UserId),
    'messages' : IDL.Vec(Message),
    'isGroup' : IDL.Bool,
    'groupName' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addContact' : IDL.Func([UserId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createConversation' : IDL.Func(
        [IDL.Vec(UserId), IDL.Bool, IDL.Opt(IDL.Text)],
        [ConversationId],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContacts' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
    'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'getMessages' : IDL.Func(
        [ConversationId, IDL.Nat, IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [UserProfile], ['query']),
    'getUserProfile' : IDL.Func([UserId], [UserProfile], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markMessagesRead' : IDL.Func([ConversationId], [], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removeContact' : IDL.Func([UserId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([ConversationId, IDL.Text], [MessageId], []),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };